name: Audit Pull

on:
  push:
    branches:
      - main

jobs:
  setup_audit:
    name: SetupAudit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Policy Library
        uses: actions/checkout
        with:
          repository: reposaur/policy

      - name: Setup Reposaur
        uses: reposaur/setup-reposaur@main

      - name: Execute Policies
        run: |
          echo "${{ github.event }}" \
          | jq -r '.pull_request' \
          | rsr exec > report.sarif
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}

      - name: Upload Report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: report.sarif
          category: reposaur
          